name: Github-Action reusable workflows test (multi-tests)
on:
  push:
    branches:
      - "develop"
      - "release"
      - "release-**"
      - "release/**"
      - "master"
    paths-ignore:
      - ".gitcommitrules"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "develop"
      - "release"
      - "release-**"
      - "release/**"
    paths-ignore:
      - ".gitcommitrules"
      - ".gitignore"
      - "LICENSE"
      - "README.md"

jobs:

  prep-testbed_unit-test:
#    name: Prepare all unit test items
    uses: ./.github/workflows/prepare_test_items.yaml
    with:
      shell_path: scripts/ci/get-unit-test-paths.sh
      shell_arg: unix


  prep-testbed_integration-test:
#    name: Prepare all integration test items
    uses: ./.github/workflows/prepare_test_items.yaml
    with:
      shell_path: scripts/ci/get-integration-test-paths.sh
      shell_arg: unix


  run_unit-test:
#    name: Run all unit test items
    needs: prep-testbed_unit-test
    uses: ./.github/workflows/run_test_items_via_pytest.yaml
    with:
      test_type: unit-test
      all_test_items_paths: ${{needs.prep-testbed_unit-test.outputs.all_test_items}}
      debug_mode: true


  run_integration-test:
#    name: Run all integration test items. This testing would test the code with other resource or system to ensure the features work finely.
    needs: prep-testbed_integration-test
    uses: ./.github/workflows/run_test_items_via_pytest.yaml
    with:
      test_type: integration-test
      all_test_items_paths: ${{needs.prep-testbed_integration-test.outputs.all_test_items}}
      setup_http_server: true
      http_server_host: 0.0.0.0
      http_server_port: 30303
      http_server_app_module: test._http_server.app
      http_server_enter_point: app
      debug_mode: true


  unit-test_codecov:
#    name: Organize and generate the testing report and upload it to Codecov
    needs: run_unit-test
    uses: ./.github/workflows/organize_and_generate_test_cov_reports.yaml
    with:
      test_type: unit-test


  integration-test_codecov:
#    name: Organize and generate the testing report and upload it to Codecov
    needs: run_integration-test
    uses: ./.github/workflows/organize_and_generate_test_cov_reports.yaml
    with:
      test_type: integration-test


  codecov_finish:
#    name: Organize and generate the testing report and upload it to Codecov
#    if: github.ref_name == 'release' || github.ref_name == 'master'
    needs: [unit-test_codecov, integration-test_codecov]
    uses: ./.github/workflows/upload_test_cov_report.yaml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      test_type: all-test
      upload-to-codecov: true
      codecov_flags: unit,integration  # Required if 'upload-to-codecov' is true
      codecov_name: gh_workflow_template  # Required if 'upload-to-codecov' is true


  coveralls_finish:
#    name: Organize and generate the testing report and upload it to Coveralls
#    if: github.ref_name == 'release' || github.ref_name == 'master'
    needs: [unit-test_codecov, integration-test_codecov]
    uses: ./.github/workflows/upload_test_cov_report.yaml
    secrets:
      coveralls_token: ${{ secrets.COVERALLS_TOKEN }}
    with:
      test_type: all-test
      upload-to-coveralls: true


  codacy_finish:
#    name: Upload test report to Codacy to analyse and record code quality
    needs: [unit-test_codecov, integration-test_codecov]
    uses: ./.github/workflows/upload_test_cov_report.yaml
    secrets:
      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    with:
      test_type: all-test
      upload-to-codacy: true


  build_git-tag_and_create_github-release:
#    name: Build git tag and GitHub release if it needs
    if: github.event_name == 'push'
    needs: [codecov_finish, coveralls_finish, codacy_finish]
    runs-on: ubuntu-latest
#    env:
#      RELEASE_TYPE: Initial
    outputs:
      release_type: ${{ steps.release_checking.outputs.run_result }}
    steps:
      - uses: actions/checkout@v2

      - name: Build git tag and create GitHub release
        id: release_checking
        run: | 
          release=$(bash ./scripts/ci/build_get-tag_or_create_github-release.sh 'github-action-reusable-workflow' 'true')
          echo "release: $release"
          release_version=$(echo "$release" | grep -E "\[Final Running Result\] Official-Release and version: ([0-9]{1,})" | grep -E -o "([0-9]{1,})")
          echo "release_version: $release_version"
          echo "::set-output name=run_result::$(echo $release_version)"

#      - name: Export the running result as environment variable 'RELEASE_TYPE'
#        id: release_checking
#        run: |
#          echo "release: $release"
#          release_version=$(echo "$release" | grep -E "\[Final Running Result\] Official-Release and version: ([0-9]{1,})" | grep -E -o "([0-9]{1,})")
#          echo "release_version: $release_version"
#          echo "::set-output name=run_result::$(echo $release_version)"


  deploy_as_new_branch:
#    name: Create new git branch by the tagged commit
    if: ${{ github.event_name == 'push' && 
                needs.build_git-tag_and_create_github-release.outputs.release_type != 'Initial' && 
                needs.build_git-tag_and_create_github-release.outputs.release_type != 'Pre' }}
    needs: build_git-tag_and_create_github-release
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ needs.build_git-tag_and_create_github-release.outputs.release_type }}
    steps:
      - uses: actions/checkout@v2

      - name: Create new git branch by the tagged commit
        run: bash ./scripts/ci/deployment_new_version_workflow.sh 'true'


#  create_version_tag:
#    if: github.ref_name == 'release' || github.event == 'push'
#    name: Build a tag in GitHub
#    needs: [codecov_finish, coveralls_finish, codacy_finish]
#    steps:
#      - name: Get the latest version of package from '__pgk_info__' module
#        run: cat ./test_gh_workflow/__pkg_info__.py | grep -e '__version__ = "[0-9].[0-9].[0-9]*"' | grep -o '[0-9].[0-9].[0-9]*'
#
#      - name: Get the latest git tag
#        run: git describe --tag --abbrev=0 --match "v[0-9].[0-9].[0-9]*"
#
#      - name: Tag a version info on the latest commit
#        run: git tag -a 'v2.0.0' -m 'Refactor and integrate the configurations to let configurations be more shorter and clear.'
#
#      - name: Release the source code with the tag and release note
#        run: gh release create v2.0.0 --title 'v2.0.0 - More shorter and clear <0001f9f9>🍻' --notes-file .github/release-notes.md
#
#
#  build_version_branch:
#    if: github.ref_name == 'master' || github.event == 'push'
#    name: Build a Git branch as version in GitHub
#    needs: [codecov_finish, coveralls_finish, codacy_finish]
#    steps:
#      - name: Check whether it has a git tag on the latest commit or not.
#        run: |
#          git tag
#
#      - name: Do something
#        run: |
#          echo "Add git remote reference"
#          git remote add github-action_workflow-template https://github.com/Chisanan232/GitHub-Action-Template-Python.git
#
#          echo "Verify the git remote info ..."
#          git remote -v
#
#          echo "Create and switch git branch with version"
#          git checkout -b v2
#
#          echo "Push the project to GitHub as the branch"
#          git push -u github-action_workflow-template v2


#  pre-building_check:
##    name: Check about it could work finely by installing the Python package with setup.py file
#    needs: [codecov_finish, codacy_finish]
#    uses: Chisanan232/GitHub-Action-Template-Python/.github/workflows/upload_code_report_to_codacy.yaml
#    with:
#      python_package_name: smoothcrawler
#      test_import_package_code_1: import smoothcrawler as mr
#      test_import_package_code_2: from smoothcrawler.crawler import SimpleCrawler
#      test_import_package_code_3: from smoothcrawler.components.data import BaseHTTPResponseParser, BaseDataHandler
#      test_python_script: ./scripts/test_crawler.py

