############################################################################
#
# Workflow Description:
#     Upload the testing coverage reports to Codacy.
#
# Workflow input parameters:
#     * General arguments:
#         * download_path: The path to download testing coverage reports via 'actions/download-artifact@v3'.
#
#     * Secret arguments:
#         * codacy_token: The API token for uploading testing coverage report to Codacy.
#
# Workflow running output:
#     No and do nothing.
#
############################################################################

name: Upload code detail report to Codacy

on:
  workflow_call:
    inputs:
      download_path:
        description: "The path to download testing coverage reports via 'actions/download-artifact@v3'."
        type: string
        required: false
        default: ./

    secrets:
      codacy_token:
        description: "The API token for uploading testing coverage report to Codacy."
        required: true


jobs:
  upload_code_to_codacy_check_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download testing coverage report
        uses: actions/download-artifact@v3
        with:
          name: final_project_testing_coverage_xml_report
          path: ${{ inputs.download_path }}

      - name: Upload testing report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.codacy_token }}
#          coverage-reports: coverage_unit-test.xml,coverage_integration-test.xml
          coverage-reports: coverage_all-test.xml
#          coverage-reports: cobertura.xml

