############################################################################
#
# Workflow Description:
#     Upload the testing coverage reports to Codecov.
#
# Workflow input parameters:
#     * General arguments:
#         * download_path: The path to download testing coverage reports via 'actions/download-artifact@v3'.
#         * upload-to-codecov: If it's true, it would upload testing coverage report for Codecov (https://codecov.io).
#         * upload-to-coveralls: If it's true, it would upload testing coverage report for Coveralls (https://coveralls.io).
#         * upload-to-codacy: If it's true, it would upload testing coverage report for Codacy (https://app.codacy.com/).
#
#     * Secret arguments:
#         * codecov_token: The API token for uploading testing coverage report to Codecov.
#         * coveralls_token: The API token for uploading testing coverage report to Coveralls.
#         * codacy_token: The API token for uploading testing coverage report to Codacy.
#
# Workflow running output:
#     No and do nothing.
#
############################################################################

name: Upload test report to Codecov

on:
  workflow_call:
    inputs:
      download_path:
        description: "The path to download testing coverage reports via 'actions/download-artifact@v3'."
        type: string
        required: false
        default: ./
      upload-to-codecov:
        description: "If it's true, it would upload testing coverage report for Codecov (https://codecov.io)."
        type: boolean
        required: false
        default: false
      upload-to-coveralls:
        description: "If it's true, it would upload testing coverage report for Coveralls (https://coveralls.io)."
        type: boolean
        required: false
        default: false
      upload-to-codacy:
        description: "If it's true, it would upload testing coverage report for Codacy (https://app.codacy.com/)."
        type: boolean
        required: false
        default: false
#      codecov_flags:
#        description: "The flags of the testing coverage report for Codecov."
#        type: string
#        required: false
#        default: ''
#      codecov_name:
#        description: "The name of the testing coverage report for Codecov."
#        type: string
#        required: false
#        default: ''

    secrets:
      codecov_token:
        description: "The API token for uploading testing coverage report to Codecov."
        required: false
      coveralls_token:
        description: "The API token for uploading testing coverage report to Coveralls."
        required: false
      codacy_token:
        description: "The API token for uploading testing coverage report to Codacy."
        required: false


jobs:
  upload_test_cov_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download code coverage result files which has be handled by different test type process
        uses: actions/download-artifact@v3
        with:
          name: final_project_testing_coverage_report
          path: ${{ inputs.download_path }}

      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies about handling testing coverage report
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -U pip
          pip3 install coverage

      - name: Combine all testing code coverage result files with all test types
        run: coverage combine .coverage.*

      - name: Report testing coverage of project code
        run: coverage report -m

      - name: Report testing coverage of project code
        run: coverage xml

      - name: Install Python dependencies about tool of Codecov
        if: ${{ inputs.upload-to-codecov == true }}
        run: pip3 install codecov

      - name: Upload coverage report to Codecov https://codecov.io
        if: ${{ inputs.upload-to-codecov == true }}
#### Way 1
#        run: bash <(curl -s https://codecov.io/bash)
#### Way 2
        run: codecov -t ${{ secrets.codecov_token }}
#### Way 3
#        uses: codecov/codecov-action@v2
#        with:
#          file: .coverage
#          token: ${{ secrets.codecov_token }} # not required for public repos
#          files:  ./coverage.xml
##          flags: ${{ inputs.codecov_flags }} # optional
##          env_vars: OS,PYTHON # optional
##          name: ${{ inputs.codecov_name }} # optional
#          fail_ci_if_error: true # optional (default = false)
#          verbose: true # optional (default = false)

      - name: Install Python dependencies about tool of Coveralls
        if: ${{ inputs.upload-to-coveralls == true }}
        run: pip3 install coveralls

      - name: Upload coverage report to Coveralls https://coveralls.io
        if: ${{ inputs.upload-to-coveralls == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.coveralls_token }}
        run: coveralls --verbose

      - name: Upload testing report to Codacy https://app.codacy.com/
        if: ${{ inputs.upload-to-codacy == true }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.codacy_token }}
          coverage-reports: coverage.xml
#          coverage-reports: cobertura.xml
