############################################################################
#
# Workflow Description:
#     Upload the testing coverage reports to Codecov.
#
# Workflow input parameters:
#     * General arguments:
#         * download_path: The path to download testing coverage reports via 'actions/download-artifact@v3'.
#         * codecov_flags: The flags of the testing coverage report for Codecov.
#         * codecov_name: The name of the testing coverage report for Codecov.
#
#     * Secret arguments:
#         * codecov_token: The API token for uploading testing coverage report to Codecov.
#
# Workflow running output:
#     No and do nothing.
#
############################################################################

name: Upload test report to Codecov

on:
  workflow_call:
    inputs:
      download_path:
        description: "The path to download testing coverage reports via 'actions/download-artifact@v3'."
        required: true
        type: string
      test_type:
        description: "The testing type. In generally, it only has 2 options: 'unit-test' and 'integration-test'."
        required: true
        type: string
      codecov_flags:
        description: "The flags of the testing coverage report for Codecov."
        required: true
        type: string
      codecov_name:
        description: "The name of the testing coverage report for Codecov."
        required: true
        type: string

    secrets:
      codecov_token:
        description: "The API token for uploading testing coverage report to Codecov."
        required: true


jobs:
  upload_report_to_codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download code coverage result file
        uses: actions/download-artifact@v3
        with:
          name: final_project_testing_coverage_report
          path: ${{ inputs.download_path }}

      - name: Rename the testing coverage report
        run: mv coverage_${{ inputs.test_type }}.xml coverage.xml

      - name: Upload coverage report to platform Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.codecov_token }} # not required for public repos
          files: coverage.xml # optional
#          files: coverage_${{ inputs.test_type }}.xml # optional
          flags: ${{ inputs.codecov_flags }} # optional
          name: ${{ inputs.codecov_name }} # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
